services:
  database:
    image: mysql:9.4.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=script
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --sql-mode=
      - --disable-log-bin
      - --init-file=/etc/mysql/ext.d/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./database/src:/var/lib/mysql
      - ./database/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./database/etc/mysql/ext.d:/etc/mysql/ext.d:ro
    restart: always

  script:
    build:
      context: ./script
      dockerfile: ./docker.dev/Dockerfile
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=script
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_general_ci
    volumes:
      - ./script/src:/app
      - /app/node_modules
      - /root/.cache
    depends_on:
      - database
    restart: on-failure
